### ISSUE TITLE
starkit.gridkit.load_grid() does not work with astropy 1.2.1

### ISSUE THREAD

**Issue by followthesheep** [starkit/starkit#1]
Loading the grid with astropy 1.2.1 causes a recursion error in astropy modelling

**Comment by urstrulykkr** [comment]
Yes, I had the same issue when tried. How about updating the astropy modules to any latest versions?

**Comment by urstrulykkr** [comment]
How about updating Astropy?  I mean, try it with the latest Astropy 3.1
I had faced similar issues while contributing in other projects, I tried updating the package modules and it turned out positive.

**Comment by followthesheep** [comment]
Sorry, we should have closed this issue. It was already fixed. Astropy 1.3 should work fine. Astropy 3 is not yet entirely compatible with starkit due to a memory leak issue in the Modeling framework.

**Comment by urstrulykkr** [comment]
It's fine :)  and @followthesheep  could you please review my PR for the task that you had assigned me earlier.

**Comment by urstrulykkr** [comment]
here is the PR (https://github.com/starkit/starkit/pull/50)
